---
engines:
  fixme:
    enabled: true
    config:
      strings:
        - TODO
        - FIXME
        - HACK
        - BUG
        - XXX
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
exclude_paths:
- node_modules/
- tests/
